//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleInseminacao.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bezerro
    {
        public string Sexo { get; set; }
        public int FK_Bezerro_IDRaca { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public int FK_Bezerro_IDIns { get; set; }
        public int FK_Bezerro_IDRep { get; set; }
        public int IDBezerro { get; set; }
        public int FK_Bezerro_IDVaca { get; set; }
    
        public virtual IDRaca IDRaca { get; set; }
        public virtual Vaca Vaca { get; set; }
        public virtual Inseminacao Inseminacao { get; set; }
        public virtual Reprodutor Reprodutor { get; set; }
    }
}
