//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleInseminacao.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inseminacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inseminacao()
        {
            this.Bezerro = new HashSet<Bezerro>();
        }
    
        public int FK_Inseminacao_IDRep { get; set; }
        public int FK_Inseminacao_IDFazenda { get; set; }
        public int IDInseminacao { get; set; }
        public int FK_Inseminacao_IDVaca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bezerro> Bezerro { get; set; }
        public virtual Fazenda Fazenda { get; set; }
        public virtual Reprodutor Reprodutor { get; set; }
        public virtual Vaca Vaca { get; set; }
    }
}
