//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleInseminacao.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaca()
        {
            this.Bezerro = new HashSet<Bezerro>();
            this.Inseminacao = new HashSet<Inseminacao>();
        }
    
        public Nullable<int> FK_Vaca_IDFazenda { get; set; }
        public int FK_Vaca_IDRaca { get; set; }
        public int IDVaca { get; set; }
        public string Nome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bezerro> Bezerro { get; set; }
        public virtual IDRaca IDRaca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inseminacao> Inseminacao { get; set; }
        public virtual Fazenda Fazenda { get; set; }
    }
}
